```{r, setup, include=F}
#rmarkdown::find_pandoc(version = "2.7.3")
source("global.R")
knitr::opts_chunk$set(cache = T, warning=F, message=F, comment="")
global_buffer_force <- F

# library(knitr)
# hook_output = knit_hooks$get('source')  #this is the output for code
# 
# knit_hooks$set(source = function(x, options) {
#   if (!is.null(n <- options$linewidth) & knitr::is_latex_output()) {
#     x <- strwrap(x, width = n, exdent = 4)
#   }
#   hook_output(x, options)
# })
```


# Abstract {-}
Asset allocation aims to construct applicable portfolios that follow a particular investment strategy, such as index tracking or optimal risk return. These investment strategies are formulated as equivalent constrained optimization problems whose solutions represent an optimal portfolio depending on the strategy. In practice, these problems are often difficult to solve without restrictions because the solution must be discrete or the constraints are too complex for common solvers. If one excludes constraints, the need for metaheuristics such as particle swarm optimization (PSO) arises because they have the ability to find optimal solutions to arbitrarily complex problems. In this thesis, common asset allocation problems are first explained and continuously solved to generate benchmark problems. After introducing the PSO, it is tested using the benchmark problems. Then, the PSO and its variants are used to solve unrestricted optimization problems. Finally, the most promising variant of the PSO is used to solve a discrete index tracking problem with consideration of transaction costs and a rebalancing constraint. The backtests indicate that the PSO can yield time-stable results for such problems.

# Introduction

Früher existierte nur das aktive Portfolio management welches versucht unter berücksichtigung des Zieles des Kunden ein Portfolio zu erstellen, indem der Portfoliomanager aktiv Assets gekauft und verkauft. Dieses vorgehen benötigt eine hohe expertiese des portfoliomanagers, welcher über die Finanzwelt und jedes Asset in seinem portfolio informiert sein muss. Das Ziel dieses vorgehens ist es assets die am markt für einen falschen Preis gehandelt werden auszunutzen, um Gewinne zu erzielen. Diese falschen Preise zu erkennen ist jedoch nicht trivial und wird immer schwerer, da der Markt zunehment effizienter zu werden scheint. Ein effizienter markt ist dadurch definiertt, das die angebebenen Preise von Assets jegliche Information über diese wiederspiegelt und somit ist das ausnutzen von falschen Preisen nicht mehr möglich. Durch diese Theorie ist das passive Portfolio management entstanden, welches eine quantitative strategie verfolgt in der es mehr um die gesamtheit des Portfolios geht und weniger um jedes individuelle Asset. Dieser quantitative Ansatz hat sich bewehrt, weshalb es innerhalb der letzten Jahre eine zunehmende Verschiebung in das passive Portfoliomanagement gab. Im Jahre 2014 wurden 18% aller Funds passiv gemanaged und dies ist im Jahre 2018 bereits auf 25% angestiegen [@TaDe2019]. Der grund dafür ist vielseitig, zum einen ist das passive management dadurch gekennzeichnet, das viele der quantitativen Strategien rein Datengesteuert funktionieren, welches durch die Automatisierbarkeit erheblich die Kosten minimiert, da nun wenige Portfoliomanager mehr Portfolios verwalten können. Zusätzlich sind passiv gemanagte portfolios offt dadurch gekennzeichnet, das sie weniger Umschichten als aktiv gemanagte Portfolios, was die Transaktionskosten geringer hält. Neben den geringeren Kosten für passive Portfolios, hat sich auch gezeigt, das diese weniger Risiko behaftet sind, was für viele Investoren von hoher Interesse ist. 



In the past, only active portfolio management existed, where the portfolio manager actively bought and sold assets in an attempt to create a portfolio with the client's objective in mind. This approach requires a high level of expertise of the portfolio manager, who must be informed about the financial world and each asset in his portfolio. The goal of this approach is to take advantage of assets that are trading in the market for the wrong price in order to make a profit. However, identifying these false prices is not trivial and is becoming increasingly difficult as the market seems to be becoming more efficient. An efficient market is defined by the fact that the quoted prices of assets reflect any information about them and thus the exploitation of false prices is no longer possible. This theory has given rise to passive portfolio management, which is a quantitative strategy that focuses more on the portfolio as a whole and less on each individual asset. This quantitative approach has proven itself, which is why there has been an increasing shift towards passive portfolio management in recent years. In 2014, 18% of all funds were passively managed and this has already increased to 25% in 2018 [@TaDe2019]. The reason for this is multifaceted, firstly passive management is characterized by the fact that many of the quantitative strategies are purely data-driven, which significantly minimizes costs through automation, as now few portfolio managers can manage more portfolios. In addition, passively managed portfolios are often characterized by less rebalancing than actively managed portfolios, which keeps transaction costs lower. In addition to the lower costs of passive portfolios, they have also been shown to be less risky, which is of high interest to many investors.





Ein Portfoliomanager der eine quantitative Strategie verfolgt und vor hat sein Portfolio kosteneffizient komplett automatisiert zu erstellen wird dabei vor eine große Herausforderung gestellt, die oftmals nur mit Einschränkungen mathematisch lösbar ist. Um diese Problemen ohne Einschränkungen zu lösen, können Metaheustiken wie das PSO Abhilfe schaffen. Sie ermöglichen es eine Lösung für ein beliebig kompliziertes Problem zu liefern, können dabei aber keine aussage über die Qualität geben. Das hat zur folge, das diese Verfahren intensiv getestet werden müssen. Es hat sich gezeigt, dass das PSO dabei zu den besten Verfahren gehört, um Portfolio optimierungs Probleme zu lösen, die nicht analytisch lösbar sind. Aus diesem Grund ist die Anwendung des PSOs in finanzmathematischen Problemen der Schwerpunkt dieser Thesis. Dazu gehört zudem das ein tiefgehendes Verständnis über das Verhalten des PSOs entwickelt werden soll, um es dem Leser zu ermöglichen das PSO auch selbst anzuwenden. Dies wird unterstützt dadurch das der Code für diese Thesis frei zugänglich ist und alle Daten kostenlos über Yahoo-Finance gedownloaded werden können. 

Ein weiteres Ziel dieser Thesis ist es dem leser die Programmiersprache R näherzubringen, da sie meiner meinung nach perfekt für solche zwecke genutzt werden kann. Ein riesen vorteil von R ist das es anwenderfreundlich ist und selbst kompliziertes einfach formuliert werden kann. Ich bin der Meinung das R es verdient hätte deutlich mehr in der Öffentlichkeit zu stehen, da es in vielen Gebieten Vorteile bezüglich anderen programmiersprachen wie Python hat.



Die Thesis fängt vorerst damit an grundlegende Informationen über die verwendete Software zu beschreiben und anschließend wird auf die freie verfügbarkeit der Daten eingegangen, welches zusammen die reproduzierbarkeit gewahrleisten soll. Danach werden die mathematischen Grundlagen und Konventionen im Kapitel "Matrix Algebra for Finance" erläutert. Darauf folgt im Kapitel "Active vs Passive Investing" eine analyse der beiden Investitionsstrategien, welche unteranderem die grundlegenden Vorteile des passiven investments beschreiben. Im darauffolgenden Kapitel werden zwei häufig vorkommenden Probleme des passiven investments beschrieben unter die das index tracking Problem und das Markowitz optimal portfolio Problem fallen. Diese Probleme dienen in dieser Thesis als Testprobleme für das PSO, für die zuerst die optimale Lösung mittels analytischen solvern gewonnen werden muss. Dies wird im Kapitel "Analytical Solver" gemacht, zusätzlich werden dabei auch die Einschränkungen von solchen analytischen Lösungswegen angesprochen. Darauf folgt das Kernthema dieser Thesis, welches mit der Beschreibung des Standard PSOs beginnt und dessen Verhalten analysiert. Es werden die Testprobleme des vorrangenagenen Kapitels verwendet, um die Qualität des PSOs zu testen. Am Ende dieses Kapitels wird eine diskretes Problem erläutert, welche nicht mehr durch analytisch lösbar ist.



