--- 
params:
  t1: "hallo"
  t2: ""
documentclass: book
classoption: oneside
github-repo: https://github.com/AxelCode-R/Asset-Allocation-using-Particle-Swarm-Optimization-in-R
link-citations: yes
bibliography:
- book.bib
- packages.bib
site: bookdown::bookdown_site
biblio-style: apalike
editor_options:
  chunk_output_type: console
description: This GitBook is the Master Thesis of Axel Roth, which was created for the graduation at the HFT Stuttgart.
---
---
title: `r if(knitr::is_html_output()){"Asset Allocation using Particle Swarm Optimization in R"}else{""}`
---

```{r, include=FALSE, eval=FALSE}
# Sys.setenv(R_GSCMD="C:\\Program Files (x86)\\gs\\gs9.55.0\\bin\\gswin32.exe")
# #bookdown::render_book('index.Rmd', 'bookdown::pdf_book')
# bookdown::render_book('index.Rmd', 'bookdown::gitbook', new_session = F)
# # serve_book(daemon=T)
# # servr::daemon_stop(1)
# # devtools::install_github("crsh/citr")
# # citr::insert_citation()
# # git add .
# 
# if(FALSE){
#   bookdown::render_book('index.Rmd', 'bookdown::pdf_book')
#   bookdown::render_book('index.Rmd', 'bookdown::gitbook')
# }
# 
```


```{r, echo=FALSE, results='asis'}
# cat(paste0("<style> \n",paste0(readr::read_lines("my_style.css"), collapse = " \n")," </style>"))
# cat(paste0("<script type='text/javascript'> \n",paste0(readr::read_lines("script.js"), collapse = " \n")," </script>"))
```

